language: node_js
node_js:
- 6
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  app: questionarios
  api_key:
    secure: ZxUIjOh0Yr3+zjqHedk745PPOZWEvhOVx8WRc2reYjPUtMubYqLRSsLyIvM00HHWxSi+r8WGDylt3SZY0zRWNf4K+cIN8ybPEv6DvLMa9ai5P9e8Q+iITGdBhgvI/GZxVvAEATuXt2D4ypl0aOGExLGH6XTVSQPcR9bOSllxqyUdy2ArhfKkyu0l70B+YFoUdqNuX+vNHNYdV8BPAfkJPzq+LmBgC+HgmDV6ArQUWsLkgxM5DKugnQfQP3mhvO1NdaLQV6dq9pUGYEmsUnbvMayHmpsJG7jXar0CxrUz1con0280uVeswYDcBPlQHLsOQ0JATh72xvMlpDF5925D+7mJJ5iL3M8bfJkFJ4zK/RIlTpVl7lvgmv7mbYSlXb+XibTz2GrTTL7GSeqQRmSRkJAyecInZATb2pWmCpsBorDG8wMPofdwDx/kBr6+tA7bDEhgua1itwIQVIUDUaopAXhOh3o8DsNWnNW8cDikbmbCqW30suUdtUd/TYWUIRJ2qGIxXDR7iCThJi8lNlaXKEjGohtrXK4fMQ3DgwQha3gNMtNqI2W/ZwEvwGINn90ZGOgZwoDeGKkZeIMIDkeRECouS2SDHU87rWJfvsXFsFuJFsiV9YY9IwWBFuqhT+x4ve2xHXqOWLMsuSv1VXQiA+wykRtw19gCZGqjHEP9FaY=
