export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_ACTION_DASHBOARD = "LOGIN_ACTION_DASHBOARD";

export const DASHBOARD = {
    GO_TO_FORM_PAGE: "DASHBOARD_TO_GO_FORM_PAGE",
    GO_TO_REGISTRY_PATIENT_PAGE: "DASHBOARD_TO_GO_REGISTRY_PATIENT_PAGE"
};

export const PAGE_FORM = "PAGE_FORM";
export const PAGE_DASHBOARD = "PAGE_DASHBOARD";
export const PAGE_REGISTRY_PATIENT= "PAGE_REGISTRY_PATIENT";

export const REGISTRY_PATIENT_GO_TO_DASHBOARD = "REGISTRY_PATIENT_GO_TO_DASHBOARD";


